const movieActionTypes = {
    GET_MOVIESEARCH_START: 'GET_MOVIESEARCH_START',
    GET_MOVIESEARCH_SUCCESS: 'GET_MOVIESEARCH_SUCCESS',
    GET_MOVIESEARCH_FAILURE: 'GET_MOVIESEARCH_FAILURE',
    SUBMIT_FIRSTMOVIEREVIEW_START: 'SUBMIT_FIRSTMOVIEREVIEW_START',
    SUBMIT_FIRSTMOVIEREVIEW_SUCCESS: 'SUBMIT_FIRSTMOVIEREVIEW_SUCCESS',
    SUBMIT_FIRSTMOVIEREVIEW_FAILURE: 'SUBMIT_FIRSTMOVIEREVIEW_FAILURE',
    GET_REVIEWSBYMOVIEID_START: 'GET_REVIEWSBYMOVIEID_START',
    GET_REVIEWSBYMOVIEID_SUCCESS: 'GET_REVIEWSBYMOVIEID_SUCCESS',
    GET_REVIEWSBYMOVIEID_FAILURE: 'GET_REVIEWSBYMOVIEID_FAILURE'
}

export default movieActionTypes;