const movieActionTypes = {
    GET_MOVIESEARCH_START: 'GET_MOVIESEARCH_START',
    GET_MOVIESEARCH_SUCCESS: 'GET_MOVIESEARCH_SUCCESS',
    GET_MOVIESEARCH_FAILURE: 'GET_MOVIESEARCH_FAILURE',
    GET_PRIVATE_MOVIES_SEARCH_START: 'GET_PRIVATE_MOVIES_SEARCH_START',
    GET_PRIVATE_MOVIES_SEARCH_SUCCESS: 'GET_PRIVATE_MOVIES_SEARCH_SUCCESS',
    GET_PRIVATE_MOVIES_SEARCH_FAILURE: 'GET_PRIVATE_MOVIES_SEARCH_FAILURE',
    GET_PRIVATE_MOVIES_SEARCH_FAILURE_SESSION: 'GET_PRIVATE_MOVIES_SEARCH_FAILURE_SESSION',
    SUBMIT_MOVIEREVIEW_START: 'SUBMIT_MOVIEREVIEW_START',
    SUBMIT_MOVIEREVIEW_SUCCESS: 'SUBMIT_MOVIEREVIEW_SUCCESS',
    SUBMIT_MOVIEREVIEW_FAILURE: 'SUBMIT_MOVIEREVIEW_FAILURE',
    SUBMIT_MOVIEREVIEW_FAILURE_SESSION: 'SUBMIT_MOVIEREVIEW_FAILURE_SESSION',
    GET_REVIEWSBYMOVIEID_START: 'GET_REVIEWSBYMOVIEID_START',
    GET_REVIEWSBYMOVIEID_SUCCESS: 'GET_REVIEWSBYMOVIEID_SUCCESS',
    GET_REVIEWSBYMOVIEID_FAILURE: 'GET_REVIEWSBYMOVIEID_FAILURE',
    GET_REVIEWSBYMOVIEID_FAILURE_SESSION: 'GET_REVIEWSBYMOVIEID_FAILURE_SESSION'
}

export default movieActionTypes;