const movieActionTypes = {
    RESET_MOVIESEARCH: 'RESET_MOVIESEARCH',
    GET_MOVIESEARCH_START: 'GET_MOVIESEARCH_START',
    GET_MOVIESEARCH_SUCCESS: 'GET_MOVIESEARCH_SUCCESS',
    GET_MOVIESEARCH_FAILURE: 'GET_MOVIESEARCH_FAILURE',

    GET_PRIVATE_MOVIES_SEARCH_START: 'GET_PRIVATE_MOVIES_SEARCH_START',
    GET_PRIVATE_MOVIES_SEARCH_SUCCESS: 'GET_PRIVATE_MOVIES_SEARCH_SUCCESS',
    GET_PRIVATE_MOVIES_SEARCH_FAILURE: 'GET_PRIVATE_MOVIES_SEARCH_FAILURE',
    GET_PRIVATE_MOVIES_SEARCH_FAILURE_SESSION: 'GET_PRIVATE_MOVIES_SEARCH_FAILURE_SESSION',

    SUBMIT_MOVIEREVIEW_START: 'SUBMIT_MOVIEREVIEW_START',
    SUBMIT_MOVIEREVIEW_SUCCESS: 'SUBMIT_MOVIEREVIEW_SUCCESS',
    SUBMIT_MOVIEREVIEW_FAILURE: 'SUBMIT_MOVIEREVIEW_FAILURE',
    SUBMIT_MOVIEREVIEW_FAILURE_SESSION: 'SUBMIT_MOVIEREVIEW_FAILURE_SESSION',

    GET_REVIEWSBYMOVIEID_START: 'GET_REVIEWSBYMOVIEID_START',
    GET_REVIEWSBYMOVIEID_SUCCESS: 'GET_REVIEWSBYMOVIEID_SUCCESS',
    GET_REVIEWSBYMOVIEID_FAILURE: 'GET_REVIEWSBYMOVIEID_FAILURE',
    GET_REVIEWSBYMOVIEID_FAILURE_SESSION: 'GET_REVIEWSBYMOVIEID_FAILURE_SESSION',

    UPDATE_REVIEW_START: 'UPDATE_REVIEW_START',
    UPDATE_REVIEW_SUCCESS: ' UPDATE_REVIEW_SUCCESS',
    UPDATE_REVIEW_FAILURE: 'UPDATE_REVIEW_FAILURE',
    UPDATE_REVIEW_FAILURE_SESSION: 'UPDATE_REVIEW_FAILURE_SESSION',

    DELETE_REVIEW_START: 'DELETE_REVIEW_START',
    DELETE_REVIEW_SUCCESS: 'DELETE_REVIEW_SUCCESS',
    DELETE_REVIEW_FAILURE: 'DELETE_REVIEW_FAILURE',
    DELETE_REVIEW_FAILURE_SESSION: 'DELETE_REVIEW_FAILURE_SESSION',

    GET_FAVORITEMOVIEREVIEW_START: 'GET_FAVORITEMOVIEREVIEW_START',
    GET_FAVORITEMOVIEREVIEW_SUCCESS: 'GET_FAVORITEMOVIEREVIEW_SUCCESS',
    GET_FAVORITEMOVIEREVIEW_FAILURE: 'GET_FAVORITEMOVIEREVIEW_FAILURE'
    // GET_FAVORITEMOVIEREVIEW_FAILURE_SESSION: 'GET_FAVORITEMOVIEREVIEW_FAILURE_SESSION'
}

export default movieActionTypes;
