const userActionTypes = {
    LOGIN_USER_START: 'LOGIN_USER_START',
    LOGIN_USER_SUCCESS: 'LOGIN_USER_SUCCESS',
    LOGIN_USER_FAILURE: 'LOGIN_USER_FAILURE',
    REGISTER_USER_START: 'REGISTER_USER_START',
    REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
    REGISTER_USER_FAILURE: 'REGISTER_USER_FAILURE',
    GET_USERBLOGS_START: 'GET_USERBLOGS_START',
    GET_USERBLOGS_SUCCESS: 'GET_USERBLOGS_SUCCESS',
    GET_USERBLOGS_FAILURE: 'GET_USERBLOGS_FAILURE',
    LOGOUT_USER_START: 'LOGOUT_USER_START',
    LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
    LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE'
}

export default userActionTypes;